name: fcm_token_sync
description: A widget which keeps your FCM token in sync with your backend
version: 1.0.2
repository: https://github.com/netsells/flutter-fcm-token-sync

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^10.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.5.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.0.3

import_sorter:
  emojis: true
