name: fcm_token_sync
description: A widget which keeps your FCM token in sync with your backend
version: 1.0.4
repository: https://github.com/netsells/flutter-fcm-token-sync

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  firebase_messaging: ^11.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.0.3
